environment:
  matrix:
    - GENERATOR: "MSYS Makefiles"
      HUNTER: "OFF"

    - GENERATOR: "MinGW Makefiles"
      HUNTER: "ON"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017 Win64"
      HUNTER: "ON"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 14 2015 Win64"
      HUNTER: "ON"

before_build:
  # Workaround for CMake complaining about sh.exe being in PATH
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  - set PATH=C:\MinGW\bin;%PATH%
  
build_script:
  - cmake "-G%GENERATOR%" "-DHUNTER_ENABLED=%HUNTER%" .
  - cmake --build . --target iceball
  - cmake --build . --target iceball-dedi
