# CMAKE generated file: DO NOT EDIT!
# Generated by "MSYS Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /C/msys64/mingw64/bin/cmake.exe

# The command to remove a file.
RM = /C/msys64/mingw64/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /C/Users/arsdr/iceball

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /C/Users/arsdr/iceball

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/C/msys64/mingw64/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/C/msys64/mingw64/bin/cmake-gui.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /C/Users/arsdr/iceball/CMakeFiles /C/Users/arsdr/iceball/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /C/Users/arsdr/iceball/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named iceball

# Build rule for target.
iceball: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iceball
.PHONY : iceball

# fast build rule for target.
iceball/fast:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/build
.PHONY : iceball/fast

#=============================================================================
# Target rules for targets named iceball-dedi

# Build rule for target.
iceball-dedi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iceball-dedi
.PHONY : iceball-dedi

# fast build rule for target.
iceball-dedi/fast:
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/build
.PHONY : iceball-dedi/fast

#=============================================================================
# Target rules for targets named sackit

# Build rule for target.
sackit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sackit
.PHONY : sackit

# fast build rule for target.
sackit/fast:
	$(MAKE) -f xlibinc/sackit/CMakeFiles/sackit.dir/build.make xlibinc/sackit/CMakeFiles/sackit.dir/build
.PHONY : sackit/fast

src/dsp.obj: src/dsp.c.obj

.PHONY : src/dsp.obj

# target to build an object file
src/dsp.c.obj:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/dsp.c.obj
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/dsp.c.obj
.PHONY : src/dsp.c.obj

src/dsp.i: src/dsp.c.i

.PHONY : src/dsp.i

# target to preprocess a source file
src/dsp.c.i:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/dsp.c.i
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/dsp.c.i
.PHONY : src/dsp.c.i

src/dsp.s: src/dsp.c.s

.PHONY : src/dsp.s

# target to generate assembly for a file
src/dsp.c.s:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/dsp.c.s
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/dsp.c.s
.PHONY : src/dsp.c.s

src/external/bit.obj: src/external/bit.c.obj

.PHONY : src/external/bit.obj

# target to build an object file
src/external/bit.c.obj:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/external/bit.c.obj
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/external/bit.c.obj
.PHONY : src/external/bit.c.obj

src/external/bit.i: src/external/bit.c.i

.PHONY : src/external/bit.i

# target to preprocess a source file
src/external/bit.c.i:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/external/bit.c.i
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/external/bit.c.i
.PHONY : src/external/bit.c.i

src/external/bit.s: src/external/bit.c.s

.PHONY : src/external/bit.s

# target to generate assembly for a file
src/external/bit.c.s:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/external/bit.c.s
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/external/bit.c.s
.PHONY : src/external/bit.c.s

src/gl/glad.obj: src/gl/glad.c.obj

.PHONY : src/gl/glad.obj

# target to build an object file
src/gl/glad.c.obj:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/gl/glad.c.obj
.PHONY : src/gl/glad.c.obj

src/gl/glad.i: src/gl/glad.c.i

.PHONY : src/gl/glad.i

# target to preprocess a source file
src/gl/glad.c.i:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/gl/glad.c.i
.PHONY : src/gl/glad.c.i

src/gl/glad.s: src/gl/glad.c.s

.PHONY : src/gl/glad.s

# target to generate assembly for a file
src/gl/glad.c.s:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/gl/glad.c.s
.PHONY : src/gl/glad.c.s

src/gl/render.obj: src/gl/render.c.obj

.PHONY : src/gl/render.obj

# target to build an object file
src/gl/render.c.obj:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/gl/render.c.obj
.PHONY : src/gl/render.c.obj

src/gl/render.i: src/gl/render.c.i

.PHONY : src/gl/render.i

# target to preprocess a source file
src/gl/render.c.i:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/gl/render.c.i
.PHONY : src/gl/render.c.i

src/gl/render.s: src/gl/render.c.s

.PHONY : src/gl/render.s

# target to generate assembly for a file
src/gl/render.c.s:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/gl/render.c.s
.PHONY : src/gl/render.c.s

src/gl/render_img.obj: src/gl/render_img.c.obj

.PHONY : src/gl/render_img.obj

# target to build an object file
src/gl/render_img.c.obj:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/gl/render_img.c.obj
.PHONY : src/gl/render_img.c.obj

src/gl/render_img.i: src/gl/render_img.c.i

.PHONY : src/gl/render_img.i

# target to preprocess a source file
src/gl/render_img.c.i:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/gl/render_img.c.i
.PHONY : src/gl/render_img.c.i

src/gl/render_img.s: src/gl/render_img.c.s

.PHONY : src/gl/render_img.s

# target to generate assembly for a file
src/gl/render_img.c.s:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/gl/render_img.c.s
.PHONY : src/gl/render_img.c.s

src/img.obj: src/img.c.obj

.PHONY : src/img.obj

# target to build an object file
src/img.c.obj:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/img.c.obj
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/img.c.obj
.PHONY : src/img.c.obj

src/img.i: src/img.c.i

.PHONY : src/img.i

# target to preprocess a source file
src/img.c.i:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/img.c.i
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/img.c.i
.PHONY : src/img.c.i

src/img.s: src/img.c.s

.PHONY : src/img.s

# target to generate assembly for a file
src/img.c.s:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/img.c.s
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/img.c.s
.PHONY : src/img.c.s

src/json.obj: src/json.c.obj

.PHONY : src/json.obj

# target to build an object file
src/json.c.obj:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/json.c.obj
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/json.c.obj
.PHONY : src/json.c.obj

src/json.i: src/json.c.i

.PHONY : src/json.i

# target to preprocess a source file
src/json.c.i:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/json.c.i
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/json.c.i
.PHONY : src/json.c.i

src/json.s: src/json.c.s

.PHONY : src/json.s

# target to generate assembly for a file
src/json.c.s:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/json.c.s
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/json.c.s
.PHONY : src/json.c.s

src/logtxt.obj: src/logtxt.c.obj

.PHONY : src/logtxt.obj

# target to build an object file
src/logtxt.c.obj:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/logtxt.c.obj
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/logtxt.c.obj
.PHONY : src/logtxt.c.obj

src/logtxt.i: src/logtxt.c.i

.PHONY : src/logtxt.i

# target to preprocess a source file
src/logtxt.c.i:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/logtxt.c.i
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/logtxt.c.i
.PHONY : src/logtxt.c.i

src/logtxt.s: src/logtxt.c.s

.PHONY : src/logtxt.s

# target to generate assembly for a file
src/logtxt.c.s:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/logtxt.c.s
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/logtxt.c.s
.PHONY : src/logtxt.c.s

src/lua.obj: src/lua.c.obj

.PHONY : src/lua.obj

# target to build an object file
src/lua.c.obj:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/lua.c.obj
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/lua.c.obj
.PHONY : src/lua.c.obj

src/lua.i: src/lua.c.i

.PHONY : src/lua.i

# target to preprocess a source file
src/lua.c.i:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/lua.c.i
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/lua.c.i
.PHONY : src/lua.c.i

src/lua.s: src/lua.c.s

.PHONY : src/lua.s

# target to generate assembly for a file
src/lua.c.s:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/lua.c.s
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/lua.c.s
.PHONY : src/lua.c.s

src/main.obj: src/main.c.obj

.PHONY : src/main.obj

# target to build an object file
src/main.c.obj:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/main.c.obj
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/main.c.obj
.PHONY : src/main.c.obj

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/main.c.i
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/main.c.s
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/main.c.s
.PHONY : src/main.c.s

src/map.obj: src/map.c.obj

.PHONY : src/map.obj

# target to build an object file
src/map.c.obj:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/map.c.obj
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/map.c.obj
.PHONY : src/map.c.obj

src/map.i: src/map.c.i

.PHONY : src/map.i

# target to preprocess a source file
src/map.c.i:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/map.c.i
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/map.c.i
.PHONY : src/map.c.i

src/map.s: src/map.c.s

.PHONY : src/map.s

# target to generate assembly for a file
src/map.c.s:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/map.c.s
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/map.c.s
.PHONY : src/map.c.s

src/model.obj: src/model.c.obj

.PHONY : src/model.obj

# target to build an object file
src/model.c.obj:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/model.c.obj
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/model.c.obj
.PHONY : src/model.c.obj

src/model.i: src/model.c.i

.PHONY : src/model.i

# target to preprocess a source file
src/model.c.i:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/model.c.i
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/model.c.i
.PHONY : src/model.c.i

src/model.s: src/model.c.s

.PHONY : src/model.s

# target to generate assembly for a file
src/model.c.s:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/model.c.s
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/model.c.s
.PHONY : src/model.c.s

src/network.obj: src/network.c.obj

.PHONY : src/network.obj

# target to build an object file
src/network.c.obj:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/network.c.obj
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/network.c.obj
.PHONY : src/network.c.obj

src/network.i: src/network.c.i

.PHONY : src/network.i

# target to preprocess a source file
src/network.c.i:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/network.c.i
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/network.c.i
.PHONY : src/network.c.i

src/network.s: src/network.c.s

.PHONY : src/network.s

# target to generate assembly for a file
src/network.c.s:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/network.c.s
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/network.c.s
.PHONY : src/network.c.s

src/path.obj: src/path.c.obj

.PHONY : src/path.obj

# target to build an object file
src/path.c.obj:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/path.c.obj
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/path.c.obj
.PHONY : src/path.c.obj

src/path.i: src/path.c.i

.PHONY : src/path.i

# target to preprocess a source file
src/path.c.i:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/path.c.i
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/path.c.i
.PHONY : src/path.c.i

src/path.s: src/path.c.s

.PHONY : src/path.s

# target to generate assembly for a file
src/path.c.s:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/path.c.s
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/path.c.s
.PHONY : src/path.c.s

src/png.obj: src/png.c.obj

.PHONY : src/png.obj

# target to build an object file
src/png.c.obj:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/png.c.obj
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/png.c.obj
.PHONY : src/png.c.obj

src/png.i: src/png.c.i

.PHONY : src/png.i

# target to preprocess a source file
src/png.c.i:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/png.c.i
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/png.c.i
.PHONY : src/png.c.i

src/png.s: src/png.c.s

.PHONY : src/png.s

# target to generate assembly for a file
src/png.c.s:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/png.c.s
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/png.c.s
.PHONY : src/png.c.s

src/random.obj: src/random.c.obj

.PHONY : src/random.obj

# target to build an object file
src/random.c.obj:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/random.c.obj
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/random.c.obj
.PHONY : src/random.c.obj

src/random.i: src/random.c.i

.PHONY : src/random.i

# target to preprocess a source file
src/random.c.i:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/random.c.i
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/random.c.i
.PHONY : src/random.c.i

src/random.s: src/random.c.s

.PHONY : src/random.s

# target to generate assembly for a file
src/random.c.s:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/random.c.s
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/random.c.s
.PHONY : src/random.c.s

src/vecmath.obj: src/vecmath.c.obj

.PHONY : src/vecmath.obj

# target to build an object file
src/vecmath.c.obj:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/vecmath.c.obj
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/vecmath.c.obj
.PHONY : src/vecmath.c.obj

src/vecmath.i: src/vecmath.c.i

.PHONY : src/vecmath.i

# target to preprocess a source file
src/vecmath.c.i:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/vecmath.c.i
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/vecmath.c.i
.PHONY : src/vecmath.c.i

src/vecmath.s: src/vecmath.c.s

.PHONY : src/vecmath.s

# target to generate assembly for a file
src/vecmath.c.s:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/vecmath.c.s
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/vecmath.c.s
.PHONY : src/vecmath.c.s

src/wav.obj: src/wav.c.obj

.PHONY : src/wav.obj

# target to build an object file
src/wav.c.obj:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/wav.c.obj
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/wav.c.obj
.PHONY : src/wav.c.obj

src/wav.i: src/wav.c.i

.PHONY : src/wav.i

# target to preprocess a source file
src/wav.c.i:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/wav.c.i
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/wav.c.i
.PHONY : src/wav.c.i

src/wav.s: src/wav.c.s

.PHONY : src/wav.s

# target to generate assembly for a file
src/wav.c.s:
	$(MAKE) -f CMakeFiles/iceball.dir/build.make CMakeFiles/iceball.dir/src/wav.c.s
	$(MAKE) -f CMakeFiles/iceball-dedi.dir/build.make CMakeFiles/iceball-dedi.dir/src/wav.c.s
.PHONY : src/wav.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... iceball"
	@echo "... iceball-dedi"
	@echo "... sackit"
	@echo "... src/dsp.obj"
	@echo "... src/dsp.i"
	@echo "... src/dsp.s"
	@echo "... src/external/bit.obj"
	@echo "... src/external/bit.i"
	@echo "... src/external/bit.s"
	@echo "... src/gl/glad.obj"
	@echo "... src/gl/glad.i"
	@echo "... src/gl/glad.s"
	@echo "... src/gl/render.obj"
	@echo "... src/gl/render.i"
	@echo "... src/gl/render.s"
	@echo "... src/gl/render_img.obj"
	@echo "... src/gl/render_img.i"
	@echo "... src/gl/render_img.s"
	@echo "... src/img.obj"
	@echo "... src/img.i"
	@echo "... src/img.s"
	@echo "... src/json.obj"
	@echo "... src/json.i"
	@echo "... src/json.s"
	@echo "... src/logtxt.obj"
	@echo "... src/logtxt.i"
	@echo "... src/logtxt.s"
	@echo "... src/lua.obj"
	@echo "... src/lua.i"
	@echo "... src/lua.s"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/map.obj"
	@echo "... src/map.i"
	@echo "... src/map.s"
	@echo "... src/model.obj"
	@echo "... src/model.i"
	@echo "... src/model.s"
	@echo "... src/network.obj"
	@echo "... src/network.i"
	@echo "... src/network.s"
	@echo "... src/path.obj"
	@echo "... src/path.i"
	@echo "... src/path.s"
	@echo "... src/png.obj"
	@echo "... src/png.i"
	@echo "... src/png.s"
	@echo "... src/random.obj"
	@echo "... src/random.i"
	@echo "... src/random.s"
	@echo "... src/vecmath.obj"
	@echo "... src/vecmath.i"
	@echo "... src/vecmath.s"
	@echo "... src/wav.obj"
	@echo "... src/wav.i"
	@echo "... src/wav.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

